server:
  port: 9000

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true    #表示将自己注册到EurekaServer端
    fetch-registry: true   #表示从EurekaServer端抓取已有的注册信息。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka 单机版
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版