spring:
  application:
    name: foo-demo-bar
  profiles:
    active: local

server:
  port: 8081
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework:
        core: debug
#        cloud: trace