server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Riven872/Note.git #GitHub上配置中心仓库名（中心化的外部配置）
          search-paths:
            - SpringCloudConfig  #搜索目录
          username: #
          password: #
          skip-ssl-validation: true
      label: note #读取分支
  rabbitmq:
    host: 192.168.31.100
    port: 5672
    username: root
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
