server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的Rabbitmq的服务信息
        defaultRabbit:  #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置Rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.31.100
                port: 5672
                username: root
                password: 123
      bindings: #服务的整合处理
        output: #通道的名称
          destination: eduExchange  #表示要使用的Exchange的名称定义
          content-type: application/json  #设置消息类型，本次为json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 2 #设置心跳时间间隔
    lease-renewal-interval-in-seconds: 5  #间隔时间
    instance-id: send-8801.com  #在信息列表时，显示主机名称
    prefer-ip-address: true #访问的路径变为ip地址